# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-11-01 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_integraciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesoextraccion',
            name='fecha_licitaciones',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
